import type { Metadata } from "next";

import "./globals.css";

import Providers from "./providers";





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="font-poppins relative overflow-x-hidden min-h-screen">
        <div className="fixed inset-0 -z-10 bg-no-repeat bg-cover bg-center bg-fixed" style={{ backgroundImage: 'url(/bg-to-use.jpg)' }} />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
